
from django.urls import path,include
from . import views
from . import nifty_50 , nifty_midcap_150 ,nifty_next_50 , nifty_100 ,nifty_smallcap_250,nifty_midcap_100,nifty_midcap_50,nifty_smallcap_50,nifty_200


urlpatterns = [
   path('',views.index),
   path('hammer/',views.hammerf),
   path('hammer/nifty_50/',nifty_50.hammerf),
   path('hammer/midcap_150/',nifty_midcap_150.hammerf),
   path('hammer/midcap_100/',nifty_midcap_100.hammerf),
   path('hammer/midcap_50/',nifty_midcap_50.hammerf),
   path('hammer/smallcap_250/',nifty_smallcap_250.hammerf),
   path('hammer/smallcap_50/', nifty_smallcap_50.hammerf),
   path('hammer/nifty_500/',views.hammerf),
   path('hammer/nifty_200/',nifty_200.hammerf),
   path('hammer/bse_200/',nifty_200.hammerf),
   path('hammer/bse_500/',views.hammerf),
   path('hammer/nifty_100/',nifty_100.hammerf),
   path('hammer/bse_100/',nifty_100.hammerf),
   path('hammer/nifty_next_50/',nifty_next_50.hammerf),

   path('dragonfly_doji/',views.dragonfly_dojif),
   path('dragonfly_doji/nifty_50/',nifty_50.dragonfly_dojif),
   path('dragonfly_doji/midcap_150/',nifty_midcap_150.dragonfly_dojif),
   path('dragonfly_doji/midcap_100/',nifty_midcap_100.dragonfly_dojif),
   path('dragonfly_doji/midcap_50/',nifty_midcap_50.dragonfly_dojif),
   path('dragonfly_doji/smallcap_250/',nifty_smallcap_250.dragonfly_dojif),
   path('dragonfly_doji/smallcap_50/', nifty_smallcap_50.dragonfly_dojif),
   path('dragonfly_doji/nifty_500/',views.dragonfly_dojif),
   path('dragonfly_doji/nifty_200/',nifty_200.dragonfly_dojif),
   path('dragonfly_doji/bse_200/',nifty_200.dragonfly_dojif),
   path('dragonfly_doji/bse_500/',views.dragonfly_dojif),
   path('dragonfly_doji/nifty_100/',nifty_100.dragonfly_dojif),
   path('dragonfly_doji/bse_100/',nifty_100.dragonfly_dojif),
   path('dragonfly_doji/nifty_next_50/',nifty_next_50.dragonfly_dojif),

   path('white_marubozu/', views.white_marubozuf),
   path('white_marubozu/nifty_50/', nifty_50.white_marubozuf),
   path('white_marubozu/midcap_150/', nifty_midcap_150.white_marubozuf),
   path('white_marubozu/midcap_100/', nifty_midcap_100.white_marubozuf),
   path('white_marubozu/midcap_50/', nifty_midcap_50.white_marubozuf),
   path('white_marubozu/smallcap_250/', nifty_smallcap_250.white_marubozuf),
   path('white_marubozu/smallcap_50/', nifty_smallcap_50.white_marubozuf),
   path('white_marubozu/nifty_500/', views.white_marubozuf),
   path('white_marubozu/nifty_200/', nifty_200.white_marubozuf),
   path('white_marubozu/bse_200/', nifty_200.white_marubozuf),
   path('white_marubozu/bse_500/', views.white_marubozuf),
   path('white_marubozu/nifty_100/', nifty_100.white_marubozuf),
   path('white_marubozu/bse_100/', nifty_100.white_marubozuf),
   path('white_marubozu/nifty_next_50/', nifty_next_50.white_marubozuf),

   path('bullish_engulfing/',views.bullish_engulfingf),
   path('bullish_engulfing/nifty_50/',nifty_50.bullish_engulfingf),
   path('bullish_engulfing/midcap_150/',nifty_midcap_150.bullish_engulfingf),
   path('bullish_engulfing/midcap_100/',nifty_midcap_100.bullish_engulfingf),
   path('bullish_engulfing/midcap_50/',nifty_midcap_50.bullish_engulfingf),
   path('bullish_engulfing/smallcap_250/',nifty_smallcap_250.bullish_engulfingf),
   path('bullish_engulfing/smallcap_50/', nifty_smallcap_50.bullish_engulfingf),
   path('bullish_engulfing/nifty_500/',views.bullish_engulfingf),
   path('bullish_engulfing/nifty_200/',nifty_200.bullish_engulfingf),
   path('bullish_engulfing/bse_200/',nifty_200.bullish_engulfingf),
   path('bullish_engulfing/bse_500/',views.bullish_engulfingf),
   path('bullish_engulfing/nifty_100/',nifty_100.bullish_engulfingf),
   path('bullish_engulfing/bse_100/',nifty_100.bullish_engulfingf),
   path('bullish_engulfing/nifty_next_50/',nifty_next_50.bullish_engulfingf),

   path('bullish_harami/',views.bullish_haramif),
   path('bullish_harami/nifty_50/',nifty_50.bullish_haramif),
   path('bullish_harami/midcap_150/',nifty_midcap_150.bullish_haramif),
   path('bullish_harami/midcap_100/',nifty_midcap_100.bullish_haramif),
   path('bullish_harami/midcap_50/',nifty_midcap_50.bullish_haramif),
   path('bullish_harami/smallcap_250/',nifty_smallcap_250.bullish_haramif),
   path('bullish_harami/smallcap_50/', nifty_smallcap_50.bullish_haramif),
   path('bullish_harami/nifty_500/',views.bullish_haramif),
   path('bullish_harami/nifty_200/',nifty_200.bullish_haramif),
   path('bullish_harami/bse_200/',nifty_200.bullish_haramif),
   path('bullish_harami/bse_500/',views.bullish_haramif),
   path('bullish_harami/nifty_100/',nifty_100.bullish_haramif),
   path('bullish_harami/bse_100/',nifty_100.bullish_haramif),
   path('bullish_harami/nifty_next_50/',nifty_next_50.bullish_haramif),

   path('rising_sun/', views.rising_sunf),
   path('rising_sun/nifty_50/', nifty_50.rising_sunf),
   path('rising_sun/midcap_150/', nifty_midcap_150.rising_sunf),
   path('rising_sun/midcap_100/', nifty_midcap_100.rising_sunf),
   path('rising_sun/midcap_50/', nifty_midcap_50.rising_sunf),
   path('rising_sun/smallcap_250/', nifty_smallcap_250.rising_sunf),
   path('rising_sun/smallcap_50/', nifty_smallcap_50.rising_sunf),
   path('rising_sun/nifty_500/', views.rising_sunf),
   path('rising_sun/nifty_200/', nifty_200.rising_sunf),
   path('rising_sun/bse_200/', nifty_200.rising_sunf),
   path('rising_sun/bse_500/', views.rising_sunf),
   path('rising_sun/nifty_100/', nifty_100.rising_sunf),
   path('rising_sun/bse_100/', nifty_100.rising_sunf),
   path('rising_sun/nifty_next_50/', nifty_next_50.rising_sunf),

   path('morning_star/',views.morning_starf),
   path('morning_star/nifty_50/',nifty_50.morning_starf),
   path('morning_star/midcap_150/',nifty_midcap_150.morning_starf),
   path('morning_star/midcap_100/',nifty_midcap_100.morning_starf),
   path('morning_star/midcap_50/',nifty_midcap_50.morning_starf),
   path('morning_star/smallcap_250/',nifty_smallcap_250.morning_starf),
   path('morning_star/smallcap_50/', nifty_smallcap_50.morning_starf),
   path('morning_star/nifty_500/',views.morning_starf),
   path('morning_star/nifty_200/',nifty_200.morning_starf),
   path('morning_star/bse_200/',nifty_200.morning_starf),
   path('morning_star/bse_500/',views.morning_starf),
   path('morning_star/nifty_100/',nifty_100.morning_starf),
   path('morning_star/bse_100/',nifty_100.morning_starf),
   path('morning_star/nifty_next_50/',nifty_next_50.morning_starf),

   path('three_white_soliders/',views.three_white_solidersf),
   path('three_white_soliders/nifty_50/',nifty_50.three_white_solidersf),
   path('three_white_soliders/midcap_150/',nifty_midcap_150.three_white_solidersf),
   path('three_white_soliders/midcap_100/',nifty_midcap_100.three_white_solidersf),
   path('three_white_soliders/midcap_50/',nifty_midcap_50.three_white_solidersf),
   path('three_white_soliders/smallcap_250/',nifty_smallcap_250.three_white_solidersf),
   path('three_white_soliders/smallcap_50/', nifty_smallcap_50.three_white_solidersf),
   path('three_white_soliders/nifty_500/',views.three_white_solidersf),
   path('three_white_soliders/nifty_200/',nifty_200.three_white_solidersf),
   path('three_white_soliders/bse_200/',nifty_200.three_white_solidersf),
   path('three_white_soliders/bse_500/',views.three_white_solidersf),
   path('three_white_soliders/nifty_100/',nifty_100.three_white_solidersf),
   path('three_white_soliders/bse_100/',nifty_100.three_white_solidersf),
   path('three_white_soliders/nifty_next_50/',nifty_next_50.three_white_solidersf),

   path('inverted_hammer/',views.inverted_hammerf),
   path('inverted_hammer/nifty_50/',nifty_50.inverted_hammerf),
   path('inverted_hammer/midcap_150/',nifty_midcap_150.inverted_hammerf),
   path('inverted_hammer/midcap_100/',nifty_midcap_100.inverted_hammerf),
   path('inverted_hammer/midcap_50/',nifty_midcap_50.inverted_hammerf),
   path('inverted_hammer/smallcap_250/',nifty_smallcap_250.inverted_hammerf),
   path('inverted_hammer/smallcap_50/', nifty_smallcap_50.inverted_hammerf),
   path('inverted_hammer/nifty_500/',views.inverted_hammerf),
   path('inverted_hammer/nifty_200/',nifty_200.inverted_hammerf),
   path('inverted_hammer/bse_200/',nifty_200.inverted_hammerf),
   path('inverted_hammer/bse_500/',views.inverted_hammerf),
   path('inverted_hammer/nifty_100/',nifty_100.inverted_hammerf),
   path('inverted_hammer/bse_100/',nifty_100.inverted_hammerf),
   path('inverted_hammer/nifty_next_50/',nifty_next_50.inverted_hammerf),

   path('gravestone_doji/',views.gravestone_dojif),
   path('gravestone_doji/nifty_50/',nifty_50.gravestone_dojif),
   path('gravestone_doji/midcap_150/',nifty_midcap_150.gravestone_dojif),
   path('gravestone_doji/midcap_100/',nifty_midcap_100.gravestone_dojif),
   path('gravestone_doji/midcap_50/',nifty_midcap_50.gravestone_dojif),
   path('gravestone_doji/smallcap_250/',nifty_smallcap_250.gravestone_dojif),
   path('gravestone_doji/smallcap_50/', nifty_smallcap_50.gravestone_dojif),
   path('gravestone_doji/nifty_500/',views.gravestone_dojif),
   path('gravestone_doji/nifty_200/',nifty_200.gravestone_dojif),
   path('gravestone_doji/bse_200/',nifty_200.gravestone_dojif),
   path('gravestone_doji/bse_500/',views.gravestone_dojif),
   path('gravestone_doji/nifty_100/',nifty_100.gravestone_dojif),
   path('gravestone_doji/bse_100/',nifty_100.gravestone_dojif),
   path('gravestone_doji/nifty_next_50/',nifty_next_50.gravestone_dojif),

   path('black_marubozu/', views.black_marubozuf),
   path('black_marubozu/nifty_50/', nifty_50.black_marubozuf),
   path('black_marubozu/midcap_150/', nifty_midcap_150.black_marubozuf),
   path('black_marubozu/midcap_100/', nifty_midcap_100.black_marubozuf),
   path('black_marubozu/midcap_50/', nifty_midcap_50.black_marubozuf),
   path('black_marubozu/smallcap_250/', nifty_smallcap_250.black_marubozuf),
   path('black_marubozu/smallcap_50/', nifty_smallcap_50.black_marubozuf),
   path('black_marubozu/nifty_500/', views.black_marubozuf),
   path('black_marubozu/nifty_200/', nifty_200.black_marubozuf),
   path('black_marubozu/bse_200/', nifty_200.black_marubozuf),
   path('black_marubozu/bse_500/', views.black_marubozuf),
   path('black_marubozu/nifty_100/', nifty_100.black_marubozuf),
   path('black_marubozu/bse_100/', nifty_100.black_marubozuf),
   path('black_marubozu/nifty_next_50/', nifty_next_50.black_marubozuf),

   path('bearish_engulfing/',views.bearish_engulfingf),
   path('bearish_engulfing/nifty_50/',nifty_50.bearish_engulfingf),
   path('bearish_engulfing/midcap_150/',nifty_midcap_150.bearish_engulfingf),
   path('bearish_engulfing/midcap_100/',nifty_midcap_100.bearish_engulfingf),
   path('bearish_engulfing/midcap_50/',nifty_midcap_50.bearish_engulfingf),
   path('bearish_engulfing/smallcap_250/',nifty_smallcap_250.bearish_engulfingf),
   path('bearish_engulfing/smallcap_50/', nifty_smallcap_50.bearish_engulfingf),
   path('bearish_engulfing/nifty_500/',views.bearish_engulfingf),
   path('bearish_engulfing/nifty_200/',nifty_200.bearish_engulfingf),
   path('bearish_engulfing/bse_200/',nifty_200.bearish_engulfingf),
   path('bearish_engulfing/bse_500/',views.bearish_engulfingf),
   path('bearish_engulfing/nifty_100/',nifty_100.bearish_engulfingf),
   path('bearish_engulfing/bse_100/',nifty_100.bearish_engulfingf),
   path('bearish_engulfing/nifty_next_50/',nifty_next_50.bearish_engulfingf),

   path('bearish_harami/', views.bearish_haramif),
   path('bearish_harami/nifty_50/', nifty_50.bearish_haramif),
   path('bearish_harami/midcap_150/', nifty_midcap_150.bearish_haramif),
   path('bearish_harami/midcap_100/', nifty_midcap_100.bearish_haramif),
   path('bearish_harami/midcap_50/', nifty_midcap_50.bearish_haramif),
   path('bearish_harami/smallcap_250/', nifty_smallcap_250.bearish_haramif),
   path('bearish_harami/smallcap_50/', nifty_smallcap_50.bearish_haramif),
   path('bearish_harami/nifty_500/', views.bearish_haramif),
   path('bearish_harami/nifty_200/', nifty_200.bearish_haramif),
   path('bearish_harami/bse_200/', nifty_200.bearish_haramif),
   path('bearish_harami/bse_500/', views.bearish_haramif),
   path('bearish_harami/nifty_100/', nifty_100.bearish_haramif),
   path('bearish_harami/bse_100/', nifty_100.bearish_haramif),
   path('bearish_harami/nifty_next_50/', nifty_next_50.bearish_haramif),

   path('dark_cloud/',views.dark_cloudf),
   path('dark_cloud/nifty_50/',nifty_50.dark_cloudf),
   path('dark_cloud/midcap_150/',nifty_midcap_150.dark_cloudf),
   path('dark_cloud/midcap_100/',nifty_midcap_100.dark_cloudf),
   path('dark_cloud/midcap_50/',nifty_midcap_50.dark_cloudf),
   path('dark_cloud/smallcap_250/',nifty_smallcap_250.dark_cloudf),
   path('dark_cloud/smallcap_50/', nifty_smallcap_50.dark_cloudf),
   path('dark_cloud/nifty_500/',views.dark_cloudf),
   path('dark_cloud/nifty_200/',nifty_200.dark_cloudf),
   path('dark_cloud/bse_200/',nifty_200.dark_cloudf),
   path('dark_cloud/bse_500/',views.dark_cloudf),
   path('dark_cloud/nifty_100/',nifty_100.dark_cloudf),
   path('dark_cloud/bse_100/',nifty_100.dark_cloudf),
   path('dark_cloud/nifty_next_50/',nifty_next_50.dark_cloudf),

   path('evening_star/',views.evening_starf),
   path('evening_star/nifty_50/',nifty_50.evening_starf),
   path('evening_star/midcap_150/',nifty_midcap_150.evening_starf),
   path('evening_star/midcap_100/',nifty_midcap_100.evening_starf),
   path('evening_star/midcap_50/',nifty_midcap_50.evening_starf),
   path('evening_star/smallcap_250/',nifty_smallcap_250.evening_starf),
   path('evening_star/smallcap_50/', nifty_smallcap_50.evening_starf),
   path('evening_star/nifty_500/',views.evening_starf),
   path('evening_star/nifty_200/',nifty_200.evening_starf),
   path('evening_star/bse_200/',nifty_200.evening_starf),
   path('evening_star/bse_500/',views.evening_starf),
   path('evening_star/nifty_100/',nifty_100.evening_starf),
   path('evening_star/bse_100/',nifty_100.evening_starf),
   path('evening_star/nifty_next_50/',nifty_next_50.evening_starf),

   path('three_black_crows/', views.three_black_crowsf),
   path('three_black_crows/nifty_50/', nifty_50.three_black_crowsf),
   path('three_black_crows/midcap_150/', nifty_midcap_150.three_black_crowsf),
   path('three_black_crows/midcap_100/', nifty_midcap_100.three_black_crowsf),
   path('three_black_crows/midcap_50/', nifty_midcap_50.three_black_crowsf),
   path('three_black_crows/smallcap_250/', nifty_smallcap_250.three_black_crowsf),
   path('three_black_crows/smallcap_50/', nifty_smallcap_50.three_black_crowsf),
   path('three_black_crows/nifty_500/', views.three_black_crowsf),
   path('three_black_crows/nifty_200/', nifty_200.three_black_crowsf),
   path('three_black_crows/bse_200/', nifty_200.three_black_crowsf),
   path('three_black_crows/bse_500/', views.three_black_crowsf),
   path('three_black_crows/nifty_100/', nifty_100.three_black_crowsf),
   path('three_black_crows/bse_100/', nifty_100.three_black_crowsf),
   path('three_black_crows/nifty_next_50/', nifty_next_50.three_black_crowsf),

   path('doji/', views.dojif),
   path('doji/nifty_50/', nifty_50.dojif),
   path('doji/midcap_150/', nifty_midcap_150.dojif),
   path('doji/midcap_100/', nifty_midcap_100.dojif),
   path('doji/midcap_50/', nifty_midcap_50.dojif),
   path('doji/smallcap_250/', nifty_smallcap_250.dojif),
   path('doji/smallcap_50/', nifty_smallcap_50.dojif),
   path('doji/nifty_500/', views.dojif),
   path('doji/nifty_200/', nifty_200.dojif),
   path('doji/bse_200/', nifty_200.dojif),
   path('doji/bse_500/', views.dojif),
   path('doji/nifty_100/', nifty_100.dojif),
   path('doji/bse_100/', nifty_100.dojif),
   path('doji/nifty_next_50/', nifty_next_50.dojif),

]
